### ISSUE TITLE
Create the Wireframes and Lo-fi for the Splitcsv Page

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#14]

**Comment by tersoo-ahire** [comment]
https://www.figma.com/file/HDodbxGZGTlpZFJKqWSV2C/Team-50-Chunk-Files?node-id=431%3A149

**Comment by BBBella86** [comment]
Lo fi and Hi fi done... mobile screens in progress.
