### ISSUE TITLE
Implement/Code the Terms of service page

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#20]

**Comment by Adedamola-Adeyemo** [comment]
Waiting for designer to finish hifi design to begin coding the page

**Comment by Lois1221** [comment]
I finished the design for this page last week  Friday, apologies if i failed to let you know

**Comment by Adedamola-Adeyemo** [comment]
Alright will finish up today

**Comment by Adedamola-Adeyemo** [comment]
Code uploaded

html - termsofservice.html
css - terms.css

**Comment by Adedamola-Adeyemo** [comment]
Noted
