### ISSUE TITLE
Create the Style Guide

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#3]

**Comment by tersoo-ahire** [comment]
https://www.figma.com/file/HDodbxGZGTlpZFJKqWSV2C?node-id=22:2

**Comment by damifetsruby** [comment]
Sign up and sign in page of both web screen and mobile screen has been designed . Inclusive of lofi, hifi

**Comment by damifetsruby** [comment]
Style guide has been designed by the assigned teams
