### ISSUE TITLE
Create the Wireframes and Lo-fi for the Contact page

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#7]

**Comment by Lois1221** [comment]
@tersoo-ahire  I have done that already, any other corrections will be made when we have our next meeting on Figma

**Comment by tersoo-ahire** [comment]
https://www.figma.com/file/HDodbxGZGTlpZFJKqWSV2C/Team-50-Chunk-Files?node-id=730%3A912
