### ISSUE TITLE
Create the Wireframes and Lo-fi for the Sign In and Sign up page

### ISSUE THREAD

**Issue by tersoo-ahire** [zuri-training/Chunk-File-Generator-Team-50#9]

**Comment by tersoo-ahire** [comment]
https://www.figma.com/file/HDodbxGZGTlpZFJKqWSV2C/Team-50-Chunk-Files?node-id=299%3A93

**Comment by damifetsruby** [comment]
The assigned pages has been designed. Designed both mobile and web screens

**Comment by damifetsruby** [comment]
Godlike also partake in this task
